### ISSUE TITLE
typo in TryButton.css

### ISSUE THREAD

**Issue by PeerRich** [daily-co/daily-demos#9]
`.tray-button {
  width: 44x;`

=> 

`.tray-button {
  width: 44px;`

**Comment by kimberleejohnson** [comment]
Thank you so much for flagging this, @PeerRich! I see this in our React demo [0], and I'll plan on fixing it in the next week. 

If you have any other feedback in the meantime about your experience using daily-js, I'd love to hear it. 

Thanks again, 
Kimberlee 

[0] https://github.com/daily-co/daily-demos/blob/main/react-demo/src/components/TrayButton/TrayButton.css
